### PR TITLE
Add Docker and Linux setup instructions

### LINKED ISSUE #29: Add Linux and Docker support for project
Our team would like to add support for Linux and Docker installation to the Readme as well as to the project. 
Me and @rk119 would like to work on it.

### PR DESCRIPTION
**Pull request by rk119**
Issue Resolved: #29 

- Added Linux setup instructions
- Added Docker files and setup instructions
- A separate section for environment variables setup instructions to avoid repetition

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Looks awesome.  Just a small suggestion: you have done great work by segregating the environment variables part. But it would we great if you mention somewhere at the top regarding it and then link the environment variables section. That would help the user to navigate as the readme has became really long !

**Review by irsayvid — CHANGES_REQUESTED** [review]
Steps like installing node.js, yarn through cli, setting up API and running them in local server are common in both windows and linux environments. Can we just combine the setup and highlight the key differences in both instead of repeating lines?

**Review by siddhi-244 — APPROVED** [review]
LGTM!

**Comment by akshitadixit** [comment]
@rk119 can you pull the latest changes from the main branch to your PR?

**Pull request merged**
