### PR TITLE
Add time of sunrise and sunset

### LINKED ISSUE #18: Add cards to show sunrise and sunset times
When a user searches for a certain place they will also be able to see the sunrise and sunset times on the Dashboard

Me and @kanchitank would like to get this assigned

### PR DESCRIPTION
**Pull request by Ciggzy1312**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Issue Resolved: #18 
Description: Added sunrise and sunset timings of the searched place

### CODE REVIEW

**Comment by akshitadixit** [comment]
@Ciggzy1312 @kanchitank can we remove the basic text for the times and add like a small sunrise/sunset image with temp under them on either sides of the search box above the map?

**Comment by akshitadixit** [comment]
image
sorry about the silly drawing but smth like this

**Comment by Ciggzy1312** [comment]
@akshitadixit we did make a separate issue #28 regarding this only
Can we make the changes there?

**Comment by akshitadixit** [comment]
Sure, until then please resolve conflicts.

**Comment by Swatishree-Mahapatra** [comment]
The default city is changed to 'Kolkata' but it shows 'New York' to me in the deployed preview. Can you check that @Ciggzy1312 @kanchitank? Apart from that, I think everything's alright.

**Comment by Ciggzy1312** [comment]
@Swatishree-Mahapatra we did set the city name back to what it was, but it won't be having any effect because probably some API call or something is setting the city name to "New York" which is not related to this issue

Everything rest seems to be working fine

**Comment by Swatishree-Mahapatra** [comment]
Cool! The PR looks good to me now. 
@akshitadixit kindly look into this.

**Comment by akshitadixit** [comment]
@Swatishree-Mahapatra new conflicts, welp :)

**Comment by Swatishree-Mahapatra** [comment]
@Ciggzy1312 @kanchitank kindly look into the new merge conflicts. 🙂

**Comment by Ciggzy1312** [comment]
@Swatishree-Mahapatra time for another quick review? :)

**Comment by Swatishree-Mahapatra** [comment]
The deploy is working fine and the code looks good. I guess we can go ahead with merging the PR.

**Review by akshitadixit — APPROVED** [review]
LGTM!

**Review by Swatishree-Mahapatra — APPROVED** [review]
LGTM!

**Pull request merged**
