### PR TITLE
feat: Show weather alerts #32

### PR DESCRIPTION
**Pull request by SudhanshuBlaze**
- Display severe weather alerts for a specific location if applicable.
- Displays `Title` and `description` of the weather alert, **if applicable** for that city.

Below is the example of weather alert for `Cambodia` city

Screenshot 2022-10-19 at 10 59 59 PM

**Note:** the API gets exhausted really quickly as we have very less API calls for free tier

### CODE REVIEW

**Comment by SudhanshuBlaze** [comment]
@akshitadixit please add the API key which I have sent you in the discord to **Netlify env**

**Comment by akshitadixit** [comment]
Added the key.

**Comment by SudhanshuBlaze** [comment]
Can you re-deploy the application?

**Review by aku1310 — APPROVED** [review]
Looks good to be merged!

**Pull request merged**
