### PR TITLE
Closes #13: adds dynamic map markers

### LINKED ISSUE #13: Update map markers based on weather
## Description
Update the markers in the map for showing the weather at a particular location entered by user.

### PR DESCRIPTION
**Pull request by niyoj**
## What changes have been done?
- We have made the map markers dynamic i.e. the marker which was just a red pin before is now replaced by a image of weather condition that changes depending on weather of current location.

### CODE REVIEW

**Comment by niyoj** [comment]
@akshitadixit we have created a PR that solves the issue #13 . Can you please merge it?

**Comment by niyoj** [comment]
@amv2 can you review this PR as this is improved version of previous PR which you are reviewing.

**Comment by niyoj** [comment]
@akshitadixit we think the deploy errors are there due to some environment variables missing in Netlify. Can you confirm this?

**Comment by akshitadixit** [comment]
@niyoj here is a ss of the logs that might be helpful
image

**Comment by niyoj** [comment]
@akshitadixit we have not made changes to any thing in `Forecast.js`. So, we could not figure out the problem.

**Review by A-Moses-Varghese — APPROVED** [review]
Everything looks fine! The deploy looks really cool!

**Comment by A-Moses-Varghese** [comment]
> @amv2 can you review this PR as this is improved version of previous PR which you are reviewing.

Apologies @niyoj ! I saw the deploy before the checks failed and the changes looked good! I was just waiting for the checks to all pass before approving

**Comment by niyoj** [comment]
No problem at all @amv2. Thanks for your review.

**Comment by niyoj** [comment]
@akshitadixit the deploy errors have been fixed. Can you merge this PR?

**Pull request merged**
