### PR TITLE
Autocomplete or suggest cities based on user input

### LINKED ISSUE #6: Autocomplete for cities
At the moment, when you type in a city, it won't help you finish your entry with suggestions. A cool feature would be if it had a drop down menu that suggested locations similar to the name. For example, if I type in `Cambridge`, it could tell me `Cambridge, MA, USA` or `Cambridge, UK` to help users get the right answers!

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
This PR resolves #6 and makes the following changes:
- Integrated a new [AutoComplete API](geoapify.com) (kudos to @Swatishree-Mahapatra for making this change!)
- Added a dropdown menu for suggesting locations and cities (kudos to @aku1310 !).
- Optimized some code and reduced the no of API calls to the new AutoComplete API by adding debouncing.

### CODE REVIEW

**Comment by akshitadixit** [comment]
@kanchitank good luck reviewing the PR, feel free to ask for help if needed :)

**Comment by akshitadixit** [comment]
image

**Comment by aku1310** [comment]
> image

I only see one component folder in my system, and in all the repositories (main and forked), there are two of them :grimacing:

**Comment by akshitadixit** [comment]
@kanchitank please finish your review so we can have this merged :)

**Review by kanchitank — COMMENTED** [review]
As soon as I type an alphabet, I'm getting this: "Error: city not found" error in the deploy preview.

P.S. Sorry for the delay from my end.

**Comment by aku1310** [comment]
@kanchitank please check and let me know if it's working, If not I'll send you the API Key which might be causing the issue

**Comment by Devansu-Yadav** [comment]
> As soon as I type an alphabet, I'm getting this: "Error: city not found" error in the deploy preview.
> 
> P.S. Sorry for the delay from my end.

Yes I noticed that the deploy preview is breaking. That's actually not due to our code. Actually, someone integrated a new API call(as there were a couple of PRs merged earlier 😅) but forgot to handle the API errors by setting the error state.

Check line no 121 in `App.js`, the data is fetched, but if the API does not return a 200 response, there's no code to handle the errors fetched from the API.

**Edit**: @kanchitank It seems like the API key for this newly integrated API has not been added over Netlify which might be causing the issue you were facing earlier. The API key still hasn't been added yet so it's still failing, but after @aku1310 's changes, seems like the App is not breaking any more.

**Comment by Devansu-Yadav** [comment]
> @kanchitank please check and let me know if it's working, If not I'll send you the API Key which might be causing the issue

The API key has already been added @aku1310 for the API we integrated it's not because of that.

**Review by kanchitank — APPROVED** [review]
Okay, it is working for me now and everything looks good to me! Apart from the API error that @Devansu-Yadav mentioned, that has been caused by someone else's PR.

@akshitadixit kindly look into this.

**Pull request merged**
