### PR TITLE
Enhancement: Add slider for weather forecast cards 

### PR DESCRIPTION
**Pull request by SudhanshuBlaze**
image

Enhancement for Issue #1

### CODE REVIEW

**Review by A-Moses-Varghese — APPROVED** [review]
Great job guys, the feature looks good!

Edit: @irsayvid just pointed out that slider is placed in between the "Header" and "Map" for suggested places. Just fix this issue by ordering the component correctly and we should be good to go!

**Comment by akshitadixit** [comment]
@SudhanshuBlaze conflicts and the changes suggested by Moses

**Comment by SudhanshuBlaze** [comment]
@amv2 Please review it again

**Comment by SudhanshuBlaze** [comment]
@amv2 Fixed issue and resolved conflicts please review it again

**Comment by amv2** [comment]
@SudhanshuBlaze I just had a second look and yep, the ordering is fixed. I think we should be good to go! Great job again guys!

**Review by A-Moses-Varghese — APPROVED** [review]
@SudhanshuBlaze I just had a second look and yep, the ordering is fixed. I think we should be good to go! Great job again guys!

**Comment by SudhanshuBlaze** [comment]
@akshitadixit It's ready to be merged now

**Pull request merged**
