### PR TITLE
Improve Results Card UI

### LINKED ISSUE #44: Improve the UI of the overall Results card
The UI of the Results card is pretty basic and could be improved with bigger fonts and reformatting the content.

### PR DESCRIPTION
**Pull request by rk119**
Solves Issue: #44 

- Removed 'ItemsNeeded' section and placed it below the result section
- Increased the font size of the text in the result card
- Added a separate set of icons for the weather 
- Adjusted the content in a grid format
- Added an animation gradient for the background

### CODE REVIEW

**Comment by rk119** [comment]
@akshitadixit, resolved the issue, please review the changes.

**Comment by akshitadixit** [comment]
@rk119 conflicts again 💀

**Comment by rk119** [comment]
@akshitadixit resolved the conflicts.

**Review by akshitadixit — APPROVED** [review]
Changes look good <3

**Pull request merged**
